dvrk_psm:
  PSM1:
    yaw_joint_controller:
      p: 400
      i: 0.1
      d: 6
    pitch_back_joint_controller:
      p: 300
      i: 0.1
      d: 1
    main_insertion_joint_controller:
      p: 300
      i: 0.1
      d: 1
    tool_roll_joint_controller:
      p: 5
      i: 0.1
      d: 1
    tool_pitch_joint_controller:
      p: 5
      i: 0.1
      d: 1
    tool_yaw_joint_controller:
      p: 5
      i: 0.1
      d: 1
    tool_gripper1_joint_controller:
      p: 100
      i: 0.1
      d: 1
    tool_gripper2_joint_controller:
      p: 100
      i: 0.1
      d: 1
    counterweight_joint_controller:
      p: 100
      i: 0.1
      d: 1
