mtm:
  right_outer_yaw_joint_controller:
    p: 400
    i: 20
    d: 0
  right_shoulder_pitch_joint_controller:
    p: 200
    i: 5
    d: 0
  right_elbow_pitch_joint_controller:
    p: 200
    i: 5
    d: 0
  right_wrist_platform_joint_controller:
    p: 100
    i: 20
    d: 0
  right_wrist_pitch_joint_controller:
    p: 100
    i: 20
    d: 0
  right_wrist_yaw_joint_controller:
    p: 100
    i: 20
    d: 0
  right_wrist_roll_joint_controller:
    p: 100
    i: 20
    d: 0
